### ISSUE TITLE
packages listing (only trekking image is seen others hide)

### ISSUE THREAD

**Issue by crazelzon** [nirojdyola/travelmaxguide#100]
http://john.travelmaxguide.com/destinations/index/6
plz check this link. only trekking is seen and others listing packages is hide.

**Comment by nirojdyola** [comment]
You don't have place data over there.

**Comment by crazelzon** [comment]
ok i got it. but i think we do have more than 18 trekking pacakages for trekking navbar will be in problems. how we manage it
