### ISSUE TITLE
No delete button in TMG special (admin dashboard)

### ISSUE THREAD

**Issue by crazelzon** [nirojdyola/travelmaxguide#101]
http://john.travelmaxguide.com/admin/packages/index/TMGSpecial

here you can see lots of photography trip but i dont see the delete button. if we can create the delete button we can make sure and delete unnecessary packages.

**Comment by nirojdyola** [comment]
Since package history needs to maintain, I don;t place delete. It can be publish and unpublish.

**Comment by crazelzon** [comment]
plz put delete button also
