### ISSUE TITLE
some of the itinerary button are not closed

### ISSUE THREAD

**Issue by crazelzon** [nirojdyola/travelmaxguide#104]
http://john.travelmaxguide.com/admin/packages/edit/57/Package

**Comment by nirojdyola** [comment]
Delete Button is not working in Package. Please check in tmg section as well.

**Comment by nirojdyola** [comment]
Let's check it once. Didn;t find the error.

**Comment by nirojdyola** [comment]
Design needs to be fixed , please check in live.
