### ISSUE TITLE
tracking google map (location)

### ISSUE THREAD

**Issue by crazelzon** [nirojdyola/travelmaxguide#95]
http://john.travelmaxguide.com/packages/index/56

how to update the location map or route map in the google map

**Comment by nirojdyola** [comment]
You need to check the map.goole.com

**Comment by crazelzon** [comment]
how to do this one

**Comment by nirojdyola** [comment]
http://www.kevinandamanda.com/create-a-custom-travel-map-with-google-maps/
https://www.create.net/support/how-to-pin-point-multiple-locations-on-google-maps
